<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>CertesSlim.Tests</RootNamespace>
        <NoWarn>1701;1702;1705;0618</NoWarn>
        <PublicSign>False</PublicSign>
        <OutputType>exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Data\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CertesSlim\CertesSlim.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>

</Project>
