<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>OpenCertServer.Acme.Abstractions.Tests</RootNamespace>
        <AssemblyName>opencertserver.acme.abstractions.tests</AssemblyName>
        <OutputType>exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\opencertserver.acme.abstractions\opencertserver.acme.abstractions.csproj"/>
    </ItemGroup>

</Project>
